# This is a basic workflow to build robot code.
name: CI Real Bot
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  push:
    branches: [ main ]
    paths:
      - "SigmaCode2026Project/**"
  pull_request:
    branches: [ main ]
    paths:
      - "SigmaCode2026Project/**"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call_build:
    uses: ./.github/workflows/universalbuild.yml
    with:
      project_path: SigmaCode2026Project
      java_version: '17'